# Generated by Django 4.2 on 2023-05-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(max_length=255)),
                ('name_set', models.JSONField(default=dict)),
                ('summary', models.TextField(default='Unknown')),
                ('redirectUrl', models.CharField(default='https://cmd8.vercel.app/', max_length=255)),
            ],
            options={
                'db_table': 'core_aitool',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiToolCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_set', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'core_aitool_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiToolCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('ai_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aitool')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aitoolcategory')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('ai_tool', 'category')},
            },
        ),
        migrations.AddField(
            model_name='aitool',
            name='categories',
            field=models.ManyToManyField(related_name='ai_tools', through='core.AiToolCategoryRelation', to='core.aitoolcategory'),
        ),
    ]
