# Generated by Django 4.2 on 2023-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiToolCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AiTool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(max_length=255)),
                ('name', models.JSONField(default=dict)),
                ('summary', models.TextField(default='Unknown')),
                ('redirectUrl', models.CharField(default='https://cmd8.vercel.app/', max_length=255)),
                ('categories', models.ManyToManyField(related_name='ai_tools', to='core.aitoolcategory')),
            ],
            options={
                'db_table': 'tb_aitool',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
