# Generated by Django 4.2 on 2023-05-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitoolcategory',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='aitool',
            table='core_aitool',
        ),
        migrations.AlterModelTable(
            name='aitoolcategory',
            table='core_aitool_category',
        ),
    ]
