# Generated by Django 4.2 on 2023-05-07 09:08

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='user123', max_length=150, unique=True, verbose_name='계정명')),
                ('nickname', models.CharField(max_length=100, verbose_name='닉네임')),
                ('status', models.CharField(choices=[('N', '정상'), ('R', '휴면'), ('S', '정지')], default='N', max_length=1, verbose_name='계정 상태')),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자'), ('N', '무응답')], default='N', max_length=1, null=True, verbose_name='성별')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(default='+8210-0000-0000', max_length=128, region=None, unique=True, verbose_name='핸드폰번호')),
                ('svc_use_pcy_agmt', models.CharField(choices=[('Y', '예'), ('N', '아니오')], default='N', max_length=1, verbose_name='서비스이용약관동의여부')),
                ('ps_info_proc_agmt', models.CharField(choices=[('Y', '예'), ('N', '아니오')], default='N', max_length=1, verbose_name='개인정보처리방침동의여부')),
                ('mkt_info_recv_agmt', models.CharField(choices=[('Y', '예'), ('N', '아니오')], default='N', max_length=1, verbose_name='마케팅정보수신동의여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
