# Generated by Django 4.2 on 2023-05-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('N', '정상'), ('R', '휴면'), ('S', '정지')], default='N', max_length=1, verbose_name='계정 상태'),
        ),
    ]
