# Generated by Django 4.2 on 2023-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='소셜 로그인 제공자'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='소셜 로그인 ID'),
        ),
    ]
